---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-svc
  labels: &DeploymentLabels
    app: booking-service
    service: booking-service
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: booking-service-tcp
  selector: *DeploymentLabels

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  labels: &DeploymentLabels
    app: booking-service
    service: booking-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 # how many pods we can add at a time
      maxUnavailable: 0 # maxUnavailable define how many pods can be unavailable
  minReadySeconds: 5
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels: *DeploymentLabels
  template:
    metadata:
      labels: *DeploymentLabels
