apiVersion: v1
kind: ConfigMap
metadata:
  name: airline-integration-env
  namespace: aerona
  labels: &DeploymentLabels
    app: aerona
    tier: back-end
    service: airline-integration-service
data:
  PORT: "8081"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
