apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels: &DeploymentLabels
    app: aerona
    tier: back-end
spec:
  selector:
    matchLabels: *DeploymentLabels
  template:
    metadata:
      name: auth-pod
      labels: *DeploymentLabels
    spec:
      containers:
        - name: user-service
          image: user-service:1.0.0
