stages:
  - test
  - build
  - deploy

Unit Tests:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 10
    - echo "Code coverage is 90%"
Test Build:
  stage: build
  image: maven
  script:
    - echo "Start building application ....."
    #- mvn clean install
    - echo "Building success"
Deploy to EKS:
  stage: deploy
  script:
    - echo "Deploy image to EKS"

